#Makefile para compilar telebot_Capi.o
#src/Makefile

ROOT = ../
LIB = $(ROOT)lib/
HTTP = https_lib/

telebot_Capi.o: telebot_Capi.c telebot_Capi.h
	gcc -W -Wall -I../ -c telebot_Capi.c

borra: 
	rm telebot_Capi.o
