#
#     Fichero:  lib/Makefile
#       Group:  Grupo 8
#      Author:  Juan Parada Claro, Javier Ros Raposo y Javier Sanchidrián Boza
#       Fecha:  07/dec/2020
#
# Descripcion:  Makefile para compilar todas las librerías:

#Libs:
#	https_lib
#	telebot_Capi

LIB_TELEBOT = telebot_Capi/

todo:	
	make -C $(LIB_TELEBOT)

borra:
	make -C $(LIB_TELEBOT) borra
