#lib/compile_libs

#Libs:
#	https_lib
#	telebot_Capi

todo:	
	make -C https_lib/
	make -C telebot_Capi/
	
borra:
	make -C telebot_Capi/ borra
	#Mirar el makefile antes de ejecutar las siguientes instrucciones antes de descomentar
	#make -C https_lib/ clean
	#make -C https_lib/ mbedtls_clean