#Makefile para compilar telebot_Capi.o

ROOT = ../
LIB = $(ROOT)lib/
HTTP = https_lib/

telebot_Capi.o: telebot_Capi.c telebot_Capi.h
	make $(LIB)$(HTTP)Makefile
	gcc -W -Wall -c telebot_Capi.c 

borra: 
	rm telebot_Capi.o
